#! /bin/bash

set -e 

# User inputs the dn of the certificate authority
echo "WARNING! For each of the prompts, the CN should match the hostname of the machine."
ex_ca_dn="/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=node1"  
read -p "Enter the Certificate Authority distinguished name (if empty enters \"$ex_ca_dn\"): " ca_dn && [ ! -z "$ca_dn" ] || ca_dn=$ex_ca_dn
echo -e "The CA dn is: $ca_dn"

# Create directory containing all the certificates that will be generated by this script
certs_dir=opensearch_certs
mkdir -p $certs_dir

# Generates the CA certificate
openssl genrsa -out $certs_dir/opensearch-server-1-ca-key.pem 2048
openssl req -new -x509 -sha256 -key $certs_dir/opensearch-server-1-ca-key.pem -subj "$ca_dn" -out $certs_dir/opensearch-server-1-ca.pem -days 730

# How many nodes
read -p "How many opensearch servers (node) do you have ? (if empty 1): " num_nodes && [ ! -z $num_nodes ] || num_nodes=1

# Generates the nodes
for ((i=1; i<=$num_nodes; i++)) # i in {1..$num_nodes}
do
  
  ex_node_dn="/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=node$i"  #"CN=node$i,O=Internet Widgits Pty Ltd,ST=Some-State,C=AU"
  read -p "Enter the dn of node$i (if empty enters \"$ex_node_dn\"): " node_dn && [ ! -z "$node_dn" ] || node_dn=$ex_node_dn
  read -p "What would you like to name the files? (if empty node$i): " cert_file_name && [ ! -z "$cert_file_name" ] || cert_file_name=node$i
  
  regex="CN=(.*),"
  node_cn=$(echo "$node_dn" | sed -E "s/$regex/\1/")
  echo "cn is $node_cn"
  
  openssl genrsa -out $certs_dir/$cert_file_name-key-temp.pem 2048
  openssl pkcs8 -inform PEM -outform PEM -in $certs_dir/$cert_file_name-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out $certs_dir/$cert_file_name-key.pem
  openssl req -new -key $certs_dir/$cert_file_name-key.pem -subj "$node_dn" -out $certs_dir/$cert_file_name.csr
  echo "subjectAltName=DNS:$node_cn, DNS:localhost" > $certs_dir/$cert_file_name.ext
  openssl x509 -req -in $certs_dir/$cert_file_name.csr -CA $certs_dir/opensearch-server-1-ca.pem -CAkey $certs_dir/opensearch-server-1-ca-key.pem -CAcreateserial -sha256 -out $certs_dir/$cert_file_name.pem -days 730 -extfile $certs_dir/$cert_file_name.ext
done
